name: Städkraft AB
favicon: null
layout_spectrum: 0.50705
typography_spectrum: 0.6658563269302249
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfefd'
    - '#81e458'
    - '#a0a0a1'
    - '#c7c9c8'
    - '#62705d'
  brandStrength: 1
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
