name: Städkraft AB
favicon: null
layout_spectrum: 0.4645963553339243
typography_spectrum: 0.6658563269302249
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.3632510250899941
  lightness: 0.5938933177385479
  saturation: 0.888477826025337
  rhythmicContrast: 0.3407789773773402
purpose: []
